### ISSUE TITLE
Issues with deploying AWS Parallel Cluster: error in .slurmctld

### ISSUE THREAD

**Issue by komashk** [sol-eng/aws-parallelcluster-rsw#10]
Hello!

Thank you very much for making your code available! 

I am attempting to launch it in my AWS account with a few modifications: 
- removed installation of Python, Quarto, apptainer, grafana, Prometheus in istall-rsw.sh because CloudFormation was timing out. 

- commented out the gpu queue for Slurm in the cluster config template due to the lack of availability of p3.16xlarge instances. 

These modifications are ok for my use case because I only need to test out job submission using the targets library (which I also added with its dependencies in run.R file).

However, while submitting of the sample Slurm jobs in shell works (I can see the compute nodes come up and I see the output from the job submission), I am having issues with submitting sample jobs from RStudio using the clustermq package. Specifically, here is the error that I am seeing for the head node's .slurmctld log in CloudWatch:

```
error: job_submit/lua: /opt/slurm/etc/job_submit.lua: /opt/slurm/etc/job_submit.lua:8: bad argument #1 to 'match' (string expected, got nil)
```

I am not familiar with lua plugin and lua code. What could be an issue here? 

Thank you in advance for any suggestions you might have!

**Comment by michaelmayer2** [comment]
Hello Karolina,

sorry to hear about the trouble but great to hear you find the code useful. 

If you are not using any GPU queue/partition for now, then you simply can NOT deploy `job_submit.lua` at all. It is only useful if you have both a GPU and non-GPU partition in order to automatically route GPU jobs to the GPU queue. 

While this should unblock your deployment, I am wondering what version of AWS Parallelcluster you are using ? 

It looks as if `string.match(job_desc['tres_per_job']` would be empty in your environment which I have not seen in any of my deployments so far. 

Michael.

**Comment by komashk** [comment]
Hi Michael,

Thank you very much for your quick reply! Indeed, omitting the deployment of `job_submit.lua` has resolved the issue.

I am deploying using AWS Parallel Cluster version 3.5.1 via the AWS Parallel Cluster UI (had some hiccups deploying using the pcluster Python package).
